# Generated by Django 3.0.dev20190427181822 on 2019-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('RA', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matricula')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('CPF', models.IntegerField(max_length=11, unique=True, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereco')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('telefone', models.IntegerField(max_length=11, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.IntegerField(primary_key=True, serialize=False, verbose_name='Curso')),
                ('nomeCurso', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
                ('duracao', models.CharField(max_length=20, verbose_name='Duracao do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('idProf', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacao')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('CPF', models.IntegerField(max_length=11, unique=True, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereco')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('telefone', models.IntegerField(max_length=11, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='idsite')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('CPF', models.IntegerField(max_length=11, unique=True, verbose_name='CPF')),
            ],
        ),
    ]
