# Generated by Django 3.0.dev20190427181822 on 2019-05-01 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaBD', '0004_auto_20190501_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('idCoord', models.IntegerField(primary_key=True, serialize=False, verbose_name='Coordenador')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='Sobrenome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('CPF', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='CPF')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereco')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('telefone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDisciplina', models.IntegerField(primary_key=True, serialize=False, verbose_name='Disciplina')),
                ('nomeDisc', models.CharField(max_length=50, verbose_name='Nome da disciplina')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('horario', models.DateTimeField()),
                ('cargaHoraria', models.CharField(max_length=20, verbose_name='Carga')),
            ],
        ),
    ]
